# @package _global_

defaults:
  - data: cifar10
  - model: simple_cnn
  - training: default
  - mlflow: local
  - _self_

# =============================== Application ================================ #
app_name: "e2e-ml-workflow"
mode: train # train, eval, full

# =============================== Paths ===================================== #
paths:
  data_dir: "./data"
  model_dir: "./models"
  log_dir: "./logs"
  output_dir: "./outputs"

# =============================== Logging =================================== #
log_level: "INFO"
log_file: "${paths.log_dir}/mlflow.log"
